version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: graphql-postgres
    environment:
      POSTGRES_DB: graphql_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # GraphQL Server
  server:
    build: ./server
    container_name: graphql-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=4000
      - DB_NAME=graphql_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  # React Client
  client:
    build: ./client
    container_name: graphql-client
    depends_on:
      - server
    ports:
      - "3000:80"
    environment:
      - REACT_APP_GRAPHQL_URL=http://localhost:4000/graphql

volumes:
  postgres_data:
